addSbtPlugin("org.scala-js"       % "sbt-scalajs"              % "1.5.0")
addSbtPlugin("ch.epfl.scala"      % "sbt-scalajs-bundler"      % "0.20.0")
addSbtPlugin("org.portable-scala" % "sbt-scalajs-crossproject" % "1.0.0")
// addSbtPlugin("org.scalameta"      % "sbt-scalafmt"             % "2.4.0")
// addSbtPlugin("ch.epfl.scala"      % "sbt-scalafix"             % "0.9.26")
